### ISSUE TITLE
Publish a release

### ISSUE THREAD

**Issue by fulldecent** [Genobank/genobankio-js#22]
Coordinate version number with https://docs.genobank.io/certificates/ documentation

Blocker:

- [x] Accept the COVID vaccine taxonomy before doing this

**Comment by MoMannn** [comment]
@fulldecent 

jsdelivr can deliver automatically from github and from specific branch. Meaning we can do branches like: 1.0, 1.1, 1.0-beta etc and use directly github for publishing. 
Example: https://cdn.jsdelivr.net/gh/Genobank/genobankio-js/js/genobank.min.js
We can also add SRI to the files. Generating the hash ourselfs or use a online tool: https://www.srihash.org/ 

There is only one limit. The repo cannot exceed 50Mb when using branches.
Since we currently have the compiled CLIs on the repo we unfortunately exceed this. Because of this I suggest either a seperate repo for CLIs or completly removing them from github and moving them directly onto out webpage or something like that?

Even if we don't go the jsdelivr github route but go to NPM our repo is still to big because of the compiled CLIs.

**Comment by fulldecent** [comment]
How about the normal way--just publish to NPM or GitHub Packages?

**Comment by MoMannn** [comment]
Still a problem with the repo size.

**Comment by fulldecent** [comment]
The dist folder is a 400kb js file. That won't fit on NPM packages?

**Comment by MoMannn** [comment]
If we are publishing to NPM you usually publish everything so it can get used as a lib from what I remember. @xpepermint You did the NPM releases can you shed some light.

**Comment by MoMannn** [comment]
Release available at:
https://cdn.jsdelivr.net/gh/Genobank/genobankio-js@1.0.0/js/genobank.min.js
With SRI:
```
<script src="https://cdn.jsdelivr.net/gh/Genobank/genobankio-js@1.0.0/js/genobank.min.js" integrity="sha384-smdOPeoLAGxeHmVYW10tRuOQwhqTo25QSyJdTHzP0c4wpixxTvQjJ5SQgSe1iSFL" crossorigin="anonymous"></script>
```
CLI release: https://github.com/Genobank/genobankio-js/releases/tag/1.0.0

**Comment by fulldecent** [comment]
@MoMannn please update version on documentation site to match the JS project

**Comment by fulldecent** [comment]
Please update README to include install instructions (lower on the page) that are typical for projects that publish NPM packages

**Comment by MoMannn** [comment]
@fulldecent 

https://github.com/Genobank/genobankio-js/pull/23

**Comment by MoMannn** [comment]
https://github.com/Genobank/genobankio-js/pull/24

**Comment by fulldecent** [comment]
Those are the release instructions, please move that to CONTRIBUTING.

I'm asking about install instructions, like `npm install...`
