### ISSUE TITLE
Update build instruction

### ISSUE THREAD

**Issue by fulldecent** [Genobank/genobankio-js#30]
@duribebe notes that he was unable to get this program running CLI using the provided instructions but was successful by using:

```sh
pkg ./dist/cli/main.s --out-path ./compiled -t node14-macos-arm64
```

@xpepermint  Please help to

- [ ] Explain why this didn't work 
- [ ] Update instructions

**Comment by MoMannn** [comment]
@fulldecent In every release there is an included compiled/build lib so one can use the cli directly. Other instructions are intended for developers.

**Comment by fulldecent** [comment]
Based on these notes, can you please attempt to diagnose which instruction Daniel tried following?

And can you guess if:

- he failed to fully follow the instructions (if so, how); or
- did follow the instructions but they were broken (if so, how)

?

**Comment by MoMannn** [comment]
Don't know. Everything works for me. What I am guessing is that since he was not using the already compiled libs he used the example command which is for the compiled lib and so it failed? 

If you go trough development instructions everything works. If you go trough usage instructions and use the compiled version everything works. Not sure what the problem could be.

**Comment by fulldecent** [comment]
@duribebe We can only assume that you did not follow the instructions correctly and that is why your JavaScript install did not work properly.

Please provide more details, and if they are available we can reevaluate.
